### PR TITLE
Fix key being stuck when unfocused and config not load properly during startup.

### LINKED ISSUE #51: Configs are not applied to modules on start
For example:
https://github.com/VortexCoyote/leraine-studio/blob/503ced948dc6f3db306352796a60788cfe6e5dd7/source/program/program.cpp#L240

Only here the UsePitch of AudioModule is modified. When the config file is load on the launch of the application, it is not applied to AudioModule. Note that there are other such options sharing the same problem.

### LINKED ISSUE #53: Wrong state of Alt key after using Alt+Tab to switch windows
If Alt+Tab is used, the pop of Alt key won't be captured. Consider getting the state of Alt key once it is needed or capturing kill focus message.

### PR DESCRIPTION
**Pull request by Opposite34**
This will resolve #53 as I added a ClearKey function to clear the keyboard holds when window refocuses.

Also add SetConfig function to set the all the configurations (except waveform as that rely on InnerRender) during config loading on startup which fixes #51 .

Not sure how well the code is structured so might need to move things around a bit.

### CODE REVIEW

**Comment by Opposite34** [comment]
Oh and the name `SetConfig` was used for the function because `LoadConfig` might be confusing with the `Config.Load` boolean but feel free to change it as appropriate.

**Comment by VortexCoyote** [comment]
Looks good! But as you mentioned we should look at refactoring the whole config dynamic and all. But for now I'll merge it since it will at least fix the bugs

**Comment by VortexCoyote** [comment]
Looks good! But as you mentioned we should look at refactoring the whole config dynamic and all. But for now I'll merge it since it will at least fix the bugs

**Comment by UnnamedOrange** [comment]
I'd like to argue that in both Windows 10 and Ubuntu it is possible to scroll on a unfocused window, so #53 hasn't been properly solved, I think. If possible, clearing the key states on losing focus instead of on getting focus is recommended.

**Pull request merged**
