### PR TITLE
Config feature

### LINKED ISSUE #23: Implement config file
To store all preferences + recent files

### PR DESCRIPTION
**Pull request by AncuL001**
Closes #23 

also removed `sfml:x64-` from `readme.md` since i proved that `imgui-sfml` also installs `sfml`

### CODE REVIEW

**Comment by AncuL001** [comment]
actually don't merge it yet. i'm gonna add a recent files feature with this

**Comment by AncuL001** [comment]
it doesn't yet handle cases of opening non-existent files (deleted/moved files). thinking about it, maybe i could also do fix it now..

**Comment by VortexCoyote** [comment]
Alrighty

**Comment by VortexCoyote** [comment]
let's merge this sucker!

**Pull request merged**
